
name: 'Cognito Terraform'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cognito-terraform:
    name: 'Setting Infrastructure for Cognito'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate on AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: cd ./cognito/; terraform init

    - name: Terraform Plan
      run: cd ./cognito/; terraform plan -input=false

    - name: Terraform Apply
      run: cd ./cognito/; terraform apply -auto-approve -input=false

    - name: Output User Pool ID
      id: user_pool_id
      run: echo "User Pool ID - $(terraform output -raw user_pool_id)"

    - name: Output Client ID
      id: client_id
      run: echo "User Pool ID - $(terraform output -raw client_id)"
