
name: 'Sign In Lambda Terraform'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sign-in-terraform:
    name: 'Setting Infrastructure for Sign In Lambda'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate on AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: cd ./signIn/; terraform init
      env:
        TF_VAR_clientId: ${{ secrets.COGNITO_CLIENT_ID }}
        TF_VAR_userPollId: ${{ secrets.COGNITO_USER_POOL_ID }}

    - name: Terraform Plan
      run: cd ./signIn/; terraform plan -input=false
      env:
        TF_VAR_clientId: ${{ secrets.COGNITO_CLIENT_ID }}
        TF_VAR_userPollId: ${{ secrets.COGNITO_USER_POOL_ID }}

    - name: Terraform Apply
      run: cd ./signIn/; terraform apply -auto-approve -input=false
      env:
        TF_VAR_clientId: ${{ secrets.COGNITO_CLIENT_ID }}
        TF_VAR_userPollId: ${{ secrets.COGNITO_USER_POOL_ID }}